# Generated by Django 2.1.7 on 2019-06-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColapserDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_file', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('out_time', models.CharField(blank=True, max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('anal_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StretcherDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_file_master_master', models.CharField(max_length=200)),
                ('insert_file_master_slave_one', models.CharField(max_length=200)),
                ('insert_file_master_slave_two', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('out_time', models.CharField(blank=True, max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('anal_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
