# Generated by Django 2.1.7 on 2019-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HmmerFixerDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_file', models.CharField(blank=True, max_length=200)),
                ('skipped_seqs', models.CharField(blank=True, max_length=200)),
                ('user_id', models.IntegerField()),
                ('out_name', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
