# Generated by Django 2.1.7 on 2019-06-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmmer_fixer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hmmerfixerdatabase',
            old_name='out_name',
            new_name='anal_name',
        ),
    ]
