# Generated by Django 2.1.7 on 2019-03-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb_coocurence', '0004_auto_20190315_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coocurence',
            old_name='gene1',
            new_name='gene1',
        ),
        migrations.RenameField(
            model_name='coocurence',
            old_name='gene2',
            new_name='gene2',
        ),
    ]
