# Generated by Django 2.1.7 on 2019-03-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coocurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene1', models.CharField(max_length=20)),
                ('gene2', models.CharField(max_length=20)),
                ('together', models.IntegerField()),
                ('first_only', models.IntegerField()),
                ('second_only', models.IntegerField()),
                ('neither', models.IntegerField()),
                ('pvalue', models.IntegerField()),
            ],
        ),
    ]
