# Generated by Django 2.1.7 on 2019-03-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb_coocurence', '0003_auto_20190315_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coocurence',
            name='pvalue',
            field=models.DecimalField(decimal_places=100, max_digits=500),
        ),
    ]
