# Generated by Django 2.1.7 on 2019-06-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb_coocurence', '0007_colapsedonlegionellastrains_colapsedonlegionellastrainwithingspecies_colapsedonspecieslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colapsedonlegionellastrains',
            name='gene1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colapsedonlegionellastrains',
            name='gene2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colapsedonlegionellastrainwithingspecies',
            name='gene1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colapsedonlegionellastrainwithingspecies',
            name='gene2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colapsedonspecieslevel',
            name='gene1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colapsedonspecieslevel',
            name='gene2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coocurence',
            name='gene1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coocurence',
            name='gene2',
            field=models.CharField(max_length=50),
        ),
    ]
