# Generated by Django 2.1.7 on 2019-04-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeighAnalyzDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfam_name', models.CharField(max_length=9)),
                ('neigh_size', models.IntegerField()),
                ('cut_off', models.IntegerField()),
                ('tax', models.CharField(max_length=200)),
                ('strand', models.CharField(max_length=10)),
                ('out_name', models.CharField(blank=True, max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
