# Generated by Django 2.1.7 on 2019-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_analysis', '0002_auto_20190409_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighanalyzdatabase',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
