# Generated by Django 2.1.7 on 2019-04-19 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_analysis', '0003_neighanalyzdatabase_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighanalyzdatabase',
            name='test_correction',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neighanalyzdatabase',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='neighanalyzdatabase',
            name='strand',
            field=models.CharField(max_length=200),
        ),
    ]
