# Generated by Django 2.1.7 on 2019-04-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_analysis', '0004_auto_20190419_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighanalyzdatabase',
            name='out_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
